### ISSUE TITLE
.github

### ISSUE THREAD

**Issue by weitenghuang** [scipian/eve#44]
Add 
[ISSUE_TEMPLATE.md](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)
[PULL_REQUEST_TEMPLATE.md](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)

**Comment by dragan** [comment]
Issue moved to [scipian/community #18](https://github.com/scipian/community/issues/18) via [**ZenHub**](https://www.zenhub.com/)

**Comment by dragan** [comment]
Since this correlates to multiple repos, moved to community for tracking.
