### ISSUE TITLE
Logging at elasticSearch

### ISSUE THREAD

**Issue by weitenghuang** [scipian/eve#46]
Should we use aws elasticsearch service which we will manage it at `rohr-infra` https://github.com/concur/rohr-infra/issues/5 ? 
Or should we deploy [elasticsearch](https://kubernetes.io/docs/tasks/debug-application-cluster/logging-elasticsearch-kibana/) as `DaemonSet` on our cluster ?

**Comment by dragan** [comment]
Tracking this work via scipian/community#24.
