### ISSUE TITLE
Spike: Understand challenges around China

### ISSUE THREAD

**Issue by bdmesh** [scipian/eve#49]
Investigate and create separate issues/spikes for China specific concerns... such as (but not fully inclusive of):

- Is there accessibility to Quay? (which quay)?  Or do we need to move to artifactory (and if so, do we universally move or have split path just for China)?  In theory Concur is moving to Quay, but may not be ready yet.

- How is Receipts (or any service) going to find dependency services such as profile?  If Gateway isn't going to help with internal DNS resolution, are we going to the external gateway?  Or is there different discovery that needs to happen?  Do we need to replicate anything in this VPC?  What proxies or other special routing do we need to consider for service connectivity?

- What piping do we have to do for operational (for instance exposing K8s api for deploying code into K8s in receipts account)?

- Where does Walle need to live to appropriately reach all Eve APIs?  For China, there's an optimized path between the Concur VPC in China and either Bellevue or Lynnwood.  Do we need Walle to run locally as well?

- Where does Rohr need to be deployed for China access?  Is Sydney the right place long term or just a testbed and it should move into the shared China VPC?

**Comment by dragan** [comment]
Current answers to questions in SPIKE

1. The word is still out on accesibility to quay from China, theoretically we should be able to reach it, but the latency will be bad. In the beginning it will work, but we should work out a better approach for the future by publishing images to multiple repos, based on region.

2. By re-using the modularity of the quoins, we can import an existing VPC outside of our control and the build the infrastructure on top of it. Of course, it will require some changes and make a current snowflake between other environments, but at least it's an automated/repeatable snowflake. The word is still out on whether we need to setup a proxy on the instances with the VPC peer.

3. The team will need to use a VPN to access their K8S API in China.

4. Currently walle is still central and can talk to multiple EVE API's.

5. Currently Scipian is running in ap-southeast-2 (Asia Pacific - Sydney) and can reach the cn-north-1 (China - Beijing) region. Eventually we should look into using a separate account in a China region to move it closer. For now, it's a good place to get us going.

**Comment by dragan** [comment]
View scipian/community#36 on work being tracked to better support multiple regions.
