### ISSUE TITLE
Spike: Brainstorm Eve Authentication options around "Concur" AD.

### ISSUE THREAD

**Issue by bdmesh** [scipian/eve#52]
Security has been driving hard at moving all prod system control/access from "Concur" AD domain and to "ConcurASP".  The concern is that plain “Concur” AD creds are more at risk than others, and by themselves are not secure enough to protect our product.

Slack is currently tied to "Concur" and so Walle could constitute a breach of this arrangement and could create friction down the road.   One idea (MFA) was suggested as a solution.   There is perhaps the possibility of using a different Slack team that’s tied to ConcurASP instead with a very short life time (as opposed to week-long okta access for “concur” based team).  

Let’s brainstorm 3 ideas (including possibly the ones above) on how we can address this concern, working through the scenarios to make sure we feel like we mitigate the root problem.  We’ll pick one and set it as the target that we’re working towards.  The goal is to have a solution (and backup options) before we engage in a security review.

**Comment by dragan** [comment]
Closing, being tracked as part of scipian/community#27 & scipian/walle#37
