### ISSUE TITLE
Docker multi-stage build

### ISSUE THREAD

**Issue by weitenghuang** [scipian/eve#81]
[Docker 17.05 Use multi-stage builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/)

Our current build process requires two steps: 
1. Build Eve installation binary docker image
2. Install Eve binary into release docker image

https://github.com/scipian/eve/blob/051379a49b8e7ade3a25bc070ef1cb6b9e030b67/build#L17

We should take advantage of the new feature in Docker 17.05 for [multistage-build](https://docs.docker.com/engine/userguide/eng-image/multistage-build/) with single Dockerfile like:

```
FROM golang:1.7.3
WORKDIR /go/src/github.com/alexellis/href-counter/
RUN go get -d -v golang.org/x/net/html  
COPY app.go .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:latest  
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=0 /go/src/github.com/alexellis/href-counter/app .
CMD ["./app"] 
```

**Comment by weitenghuang** [comment]
@nicklathe i remembered you mentioned this feature from your last DockerCon. right?

**Comment by weitenghuang** [comment]
We need to be aware of which engine version our CI supports.
For example from CircleCI:
https://circleci.com/docs/2.0/building-docker-images/#docker-version

**Comment by dragan** [comment]
I played with the multi-stage build functionality in #101 and didn't quite like it. I'm pretty happy with the flow as it is. Let's close this for now and maybe re-visit if the current toolchain stops working for us.
